fragment CartContent on Cart {
	contents(first: 100) {
		itemCount
		nodes {
			...CartItemContent
		}
	}
	appliedCoupons {
		code
		discountAmount
		discountTax
	}
	needsShippingAddress
	chosenShippingMethods
	availableShippingMethods {
		packageDetails
		supportsShippingCalculator
		rates {
			id
			instanceId
			methodId
			label
			cost
		}
	}
	subtotal
	subtotalTax
	shippingTax
	shippingTotal
	total(format: RAW)
	totalTax
	feeTax
	feeTotal
	discountTax
	discountTotal
}
