fragment LineItemFields on LineItem {
	id
	databaseId
	product {
		node {
			...ProductContentSlice
		}
	}
	variation {
		node {
			...ProductContentSlice
		}
	}
	quantity
	total
	subtotal
	subtotalTax
}
