fragment ProductContentFull on Product {
	id
	databaseId
	slug
	name
	type
	description
	shortDescription(format: RAW)
	image {
		id
		sourceUrl
		altText
	}
	galleryImages {
		nodes {
			id
			sourceUrl(size: WOOCOMMERCE_THUMBNAIL)
			altText
		}
	}
	productTags(first: 20) {
		nodes {
			id
			slug
			name
		}
	}
	attributes {
		nodes {
			id
			attributeId
			... on LocalProductAttribute {
				name
				label
				options
				variation
			}
			... on GlobalProductAttribute {
				name
				label
				options
				variation
				slug
				terms(first: 100) {
					nodes {
						id
						name
						slug
					}
				}
			}
		}
	}
	... on SimpleProduct {
		onSale
		stockStatus
		price
		rawPrice: price(format: RAW)
		regularPrice
		salePrice
		stockStatus
		stockQuantity
		soldIndividually
		defaultAttributes(first: 100) {
			nodes {
				id
				attributeId
				name
				value
				label
			}
		}
	}
	... on VariableProduct {
		onSale
		price
		rawPrice: price(format: RAW)
		regularPrice
		salePrice
		stockStatus
		stockQuantity
		soldIndividually
		defaultAttributes(first: 100) {
			nodes {
				id
				attributeId
				label
				name
				value
			}
		}
		variations(first: 50) {
			nodes {
				id
				databaseId
				name
				price
				rawPrice: price(format: RAW)
				regularPrice
				salePrice
				onSale
				attributes {
					nodes {
						name
						label
						value
					}
				}
				image {
					id
					sourceUrl
					altText
				}
			}
		}
	}
}
