fragment ProductContentSlice on ProductUnion {
	id
	databaseId
	name
	slug
	type
	image {
		...ThumbnailImageFields
	}
	... on ProductWithPricing {
		price
		regularPrice
		salePrice
	}
	... on InventoriedProduct {
		stockStatus
		stockQuantity
		soldIndividually
	}
}
