fragment ProductTaxonomies on Product {
	productCategories(first: 20, where: { hideEmpty: true }) {
		nodes {
			id
			slug
			name
			count
		}
	}
	productTags(first: 20, where: { hideEmpty: true }) {
		nodes {
			id
			slug
			name
			count
		}
	}
}
