fragment CartItemContent on CartItem {
	key
	product {
		node {
			...ProductContentSlice
		}
	}
	variation {
		attributes {
			id
			label
			name
			value
		}
		node {
			...ProductContentSlice
		}
	}
	quantity
	total
	subtotal
	subtotalTax
	extraData {
		key
		value
	}
}
