fragment CustomerFields on Customer {
	id
	databaseId
	firstName
	lastName
	displayName
	email
	sessionToken
	orders {
		nodes {
			...OrderFields
		}
	}
	billing {
		...AddressFields
	}
	shipping {
		...AddressFields
	}
	metaData {
		key
		value
	}
}
