query GetLayout {
  generalSettings {
    ...MyGeneralSettings
  }
  header: getHeader {
    ...HCMSHeader
  }
  footer: getFooter {
    ...HCMSFooter
  }
  headerMenu: menu(id: "hcms-menu-header", idType: LOCATION) {
    ...MenuItems
  }
  footerMenu: menu(id: "hcms-menu-footer", idType: LOCATION) {
    ...MenuItems
  }
}