query GetLayout {
	generalSettings {
		...MyGeneralSettings @mask_disable
	}
	header: getHeader {
		...HCMSHeader @mask_disable
	}
	footer: getFooter {
		...HCMSFooter @mask_disable
	}
	headerMenu: menu(id: "hcms-menu-header", idType: LOCATION) {
		...MenuItems @mask_disable
	}
	footerMenu: menu(id: "hcms-menu-footer", idType: LOCATION) {
		...MenuItems @mask_disable
	}
}
