query GetProductsMaskingTest(
	$first: Int
	$last: Int
	$after: String
	$before: String
	$where: RootQueryToProductUnionConnectionWhereArgs
) {
	products(first: $first, last: $last, after: $after, before: $before, where: $where)
		@paginate(mode: SinglePage)
		@loading {
		pageInfo {
			hasPreviousPage
			hasNextPage
			startCursor
			endCursor
		}
		edges {
			cursor
			node {
				...MyProductTaxonomies
				...MyProductContentSmall
			}
		}
		nodes {
			...MyProductTaxonomies
			...MyProductContentSmall
		}
	}
}
