query GetShopColors($first: Int, $after: String, $where: RootQueryToPaColorConnectionWhereArgs) {
	allPaColor(first: $first, after: $after, where: $where) {
		pageInfo {
			hasNextPage
			endCursor
		}
		edges {
			node {
				id
				name
				slug
			}
		}
		nodes {
			id
			name
			slug
		}
	}
}
